import { useEffect, useState } from "react";
import api from "../services/api";

const defaults = { tituloLanding:"", descripcionLanding:"", logoUrl:"", whatsApp:"", colorPrimario:"#5267df", colorSecundario:"#172033", colorFondo:"#f7f9fc", colorHeader:"#ffffff", colorFooter:"#f7f9fc", colorBoton:"#5267df", colorTexto:"#172033", heroFondoUrl:"", textoFooter:"", heroEstilo:"clasico", heroEtiqueta:"", heroTituloResaltado:"", heroImagenUrl:"" };

function LandingSettings({ onClose, onSaved }) {
  const [form,setForm]=useState(defaults); const [cargando,setCargando]=useState(true); const [guardando,setGuardando]=useState(false); const [mensaje,setMensaje]=useState(""); const [error,setError]=useState("");
  useEffect(()=>{api.get("/Configuracion/landing").then(({data})=>setForm({...defaults,...data,colorPrimario:data.colorPrimario||defaults.colorPrimario,colorSecundario:data.colorSecundario||defaults.colorSecundario,colorFondo:data.colorFondo||defaults.colorFondo,colorHeader:data.colorHeader||defaults.colorHeader,colorFooter:data.colorFooter||defaults.colorFooter,colorBoton:data.colorBoton||data.colorPrimario||defaults.colorBoton,colorTexto:data.colorTexto||defaults.colorTexto})).catch(()=>setError("No fue posible cargar la configuración.")).finally(()=>setCargando(false));},[]);
  const cambiar=e=>setForm(a=>({...a,[e.target.name]:e.target.value}));
  const guardar=async e=>{e.preventDefault();try{setGuardando(true);setError("");setMensaje("");const {data}=await api.put("/Configuracion/landing",form);setMensaje("✓ Página actualizada correctamente");onSaved?.(data.negocio);}catch(err){setError(typeof err.response?.data==="string"?err.response.data:"No fue posible guardar los cambios.");}finally{setGuardando(false);}};
  const Color=({name,label})=><label>{label}<div className="landing-color-input"><input type="color" name={name} value={form[name]} onChange={cambiar}/><span>{form[name]}</span></div></label>;
  return <div className="landing-settings-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="landing-settings-modal"><div className="landing-settings-head"><div><span>MI PÁGINA</span><h2>Personalizar página pública</h2><p>Cambia contenido, colores y apariencia de tu catálogo.</p></div><button type="button" onClick={onClose}>×</button></div>{cargando?<div className="landing-settings-loading">Cargando...</div>:<form onSubmit={guardar} className="landing-settings-form">
    <h3>Contenido</h3><label>Título principal<input name="tituloLanding" maxLength="180" value={form.tituloLanding} onChange={cambiar}/></label><label>Descripción<textarea name="descripcionLanding" maxLength="500" rows="3" value={form.descripcionLanding} onChange={cambiar}/></label><label>Logo (URL)<input name="logoUrl" maxLength="500" value={form.logoUrl} onChange={cambiar} placeholder="https://..."/></label><label>WhatsApp<input name="whatsApp" maxLength="20" value={form.whatsApp} onChange={cambiar}/></label>
    <h3>Hero principal</h3><label>Diseño<select name="heroEstilo" value={form.heroEstilo} onChange={cambiar}><option value="clasico">Clásico</option><option value="editorial">Editorial / marca fuerte</option></select></label><label>Etiqueta superior<input name="heroEtiqueta" maxLength="120" value={form.heroEtiqueta} onChange={cambiar} placeholder="Ej: SUPLEMENTOS DEPORTIVOS"/></label><label>Texto resaltado del título<input name="heroTituloResaltado" maxLength="180" value={form.heroTituloResaltado} onChange={cambiar} placeholder="Ej: RESULTADOS RAW."/></label><label>Imagen principal del Hero (URL)<input name="heroImagenUrl" maxLength="500" value={form.heroImagenUrl} onChange={cambiar} placeholder="https://..."/></label><h3>Apariencia</h3><div className="landing-color-grid"><Color name="colorPrimario" label="Color principal"/><Color name="colorSecundario" label="Color secundario"/><Color name="colorFondo" label="Fondo de página"/><Color name="colorHeader" label="Header"/><Color name="colorFooter" label="Footer"/><Color name="colorBoton" label="Botones"/><Color name="colorTexto" label="Texto principal"/></div>
    <label>Imagen de fondo del Hero (URL)<input name="heroFondoUrl" maxLength="500" value={form.heroFondoUrl} onChange={cambiar} placeholder="https://..."/></label><label>Texto del footer<input name="textoFooter" maxLength="250" value={form.textoFooter} onChange={cambiar} placeholder="Gracias por apoyar nuestro negocio ❤️"/></label>
    <div className="landing-live-preview" style={{background:form.colorFondo,color:form.colorTexto}}><div style={{background:form.colorHeader}}><strong>{form.tituloLanding||"Tu negocio"}</strong></div><section style={form.heroFondoUrl?{backgroundImage:`linear-gradient(rgba(255,255,255,.78),rgba(255,255,255,.78)),url("${form.heroFondoUrl}")`}:{}}><span style={{background:form.colorBoton}}>Ver productos</span></section><footer style={{background:form.colorFooter}}>{form.textoFooter||"Vista previa del footer"}</footer></div>
    {error&&<div className="landing-settings-error">{error}</div>}{mensaje&&<div className="landing-settings-success">{mensaje}</div>}<div className="landing-settings-actions"><button type="button" onClick={onClose}>Cancelar</button><button type="submit" disabled={guardando}>{guardando?"Guardando...":"Guardar cambios"}</button></div></form>}</div></div>;
}
export default LandingSettings;
